/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as NewsRouteImport } from './routes/news'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PortalParentRouteImport } from './routes/portal.parent'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'

const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalParentRoute = PortalParentRouteImport.update({
  id: '/portal/parent',
  path: '/portal/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/programs': typeof ProgramsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/auth/login': typeof AuthLoginRoute
  '/portal/parent': typeof PortalParentRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/programs': typeof ProgramsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/auth/login': typeof AuthLoginRoute
  '/portal/parent': typeof PortalParentRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/programs': typeof ProgramsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/auth/login': typeof AuthLoginRoute
  '/portal/parent': typeof PortalParentRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/news'
    | '/programs'
    | '/admin/students'
    | '/auth/login'
    | '/portal/parent'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/news'
    | '/programs'
    | '/admin/students'
    | '/auth/login'
    | '/portal/parent'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/news'
    | '/programs'
    | '/admin/students'
    | '/auth/login'
    | '/portal/parent'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  NewsRoute: typeof NewsRoute
  ProgramsRoute: typeof ProgramsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  PortalParentRoute: typeof PortalParentRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/parent': {
      id: '/portal/parent'
      path: '/portal/parent'
      fullPath: '/portal/parent'
      preLoaderRoute: typeof PortalParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  NewsRoute: NewsRoute,
  ProgramsRoute: ProgramsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AuthLoginRoute: AuthLoginRoute,
  PortalParentRoute: PortalParentRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
