/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebsiteIndexRouteImport } from './routes/website/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher/index'
import { Route as StockIndexRouteImport } from './routes/stock/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as FinanceIndexRouteImport } from './routes/finance/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WebsiteProgramsRouteImport } from './routes/website/programs'
import { Route as WebsiteNewsRouteImport } from './routes/website/news'
import { Route as WebsiteGalleryRouteImport } from './routes/website/gallery'
import { Route as WebsiteFaqRouteImport } from './routes/website/faq'
import { Route as WebsiteContactRouteImport } from './routes/website/contact'
import { Route as WebsiteAdmissionsRouteImport } from './routes/website/admissions'
import { Route as WebsiteAboutRouteImport } from './routes/website/about'
import { Route as TeacherTimetableRouteImport } from './routes/teacher/timetable'
import { Route as TeacherReportsRouteImport } from './routes/teacher/reports'
import { Route as TeacherMarksRouteImport } from './routes/teacher/marks'
import { Route as TeacherCoursesRouteImport } from './routes/teacher/courses'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher/attendance'
import { Route as TeacherAssignmentsRouteImport } from './routes/teacher/assignments'
import { Route as StockReportsRouteImport } from './routes/stock/reports'
import { Route as StockProductsRouteImport } from './routes/stock/products'
import { Route as StockOutRouteImport } from './routes/stock/out'
import { Route as StockNotificationsRouteImport } from './routes/stock/notifications'
import { Route as StockInRouteImport } from './routes/stock/in'
import { Route as LibraryReturnRouteImport } from './routes/library/return'
import { Route as LibraryReportsRouteImport } from './routes/library/reports'
import { Route as LibraryBorrowRouteImport } from './routes/library/borrow'
import { Route as LibraryBooksRouteImport } from './routes/library/books'
import { Route as FinanceStructureRouteImport } from './routes/finance/structure'
import { Route as FinanceReportsRouteImport } from './routes/finance/reports'
import { Route as FinanceIncomeRouteImport } from './routes/finance/income'
import { Route as FinanceFeesRouteImport } from './routes/finance/fees'
import { Route as FinanceExpensesRouteImport } from './routes/finance/expenses'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTeachersRouteImport } from './routes/admin/teachers'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminStockRouteImport } from './routes/admin/stock'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminMarksRouteImport } from './routes/admin/marks'
import { Route as AdminLibraryRouteImport } from './routes/admin/library'
import { Route as AdminHrRouteImport } from './routes/admin/hr'
import { Route as AdminFinanceRouteImport } from './routes/admin/finance'
import { Route as AdminCommunicationRouteImport } from './routes/admin/communication'
import { Route as AdminCalendarRouteImport } from './routes/admin/calendar'
import { Route as AdminAttendanceRouteImport } from './routes/admin/attendance'
import { Route as AdminAcademicsRouteImport } from './routes/admin/academics'
import { Route as WebsitePortalParentRouteImport } from './routes/website/portal.parent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteIndexRoute = WebsiteIndexRouteImport.update({
  id: '/website/',
  path: '/website/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockIndexRoute = StockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteProgramsRoute = WebsiteProgramsRouteImport.update({
  id: '/website/programs',
  path: '/website/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteNewsRoute = WebsiteNewsRouteImport.update({
  id: '/website/news',
  path: '/website/news',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteGalleryRoute = WebsiteGalleryRouteImport.update({
  id: '/website/gallery',
  path: '/website/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteFaqRoute = WebsiteFaqRouteImport.update({
  id: '/website/faq',
  path: '/website/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteContactRoute = WebsiteContactRouteImport.update({
  id: '/website/contact',
  path: '/website/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteAdmissionsRoute = WebsiteAdmissionsRouteImport.update({
  id: '/website/admissions',
  path: '/website/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteAboutRoute = WebsiteAboutRouteImport.update({
  id: '/website/about',
  path: '/website/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTimetableRoute = TeacherTimetableRouteImport.update({
  id: '/teacher/timetable',
  path: '/teacher/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherReportsRoute = TeacherReportsRouteImport.update({
  id: '/teacher/reports',
  path: '/teacher/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherMarksRoute = TeacherMarksRouteImport.update({
  id: '/teacher/marks',
  path: '/teacher/marks',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherCoursesRoute = TeacherCoursesRouteImport.update({
  id: '/teacher/courses',
  path: '/teacher/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/teacher/attendance',
  path: '/teacher/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAssignmentsRoute = TeacherAssignmentsRouteImport.update({
  id: '/teacher/assignments',
  path: '/teacher/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const StockReportsRoute = StockReportsRouteImport.update({
  id: '/stock/reports',
  path: '/stock/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const StockProductsRoute = StockProductsRouteImport.update({
  id: '/stock/products',
  path: '/stock/products',
  getParentRoute: () => rootRouteImport,
} as any)
const StockOutRoute = StockOutRouteImport.update({
  id: '/stock/out',
  path: '/stock/out',
  getParentRoute: () => rootRouteImport,
} as any)
const StockNotificationsRoute = StockNotificationsRouteImport.update({
  id: '/stock/notifications',
  path: '/stock/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const StockInRoute = StockInRouteImport.update({
  id: '/stock/in',
  path: '/stock/in',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryReturnRoute = LibraryReturnRouteImport.update({
  id: '/library/return',
  path: '/library/return',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryReportsRoute = LibraryReportsRouteImport.update({
  id: '/library/reports',
  path: '/library/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryBorrowRoute = LibraryBorrowRouteImport.update({
  id: '/library/borrow',
  path: '/library/borrow',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryBooksRoute = LibraryBooksRouteImport.update({
  id: '/library/books',
  path: '/library/books',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceStructureRoute = FinanceStructureRouteImport.update({
  id: '/finance/structure',
  path: '/finance/structure',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceReportsRoute = FinanceReportsRouteImport.update({
  id: '/finance/reports',
  path: '/finance/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIncomeRoute = FinanceIncomeRouteImport.update({
  id: '/finance/income',
  path: '/finance/income',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceFeesRoute = FinanceFeesRouteImport.update({
  id: '/finance/fees',
  path: '/finance/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceExpensesRoute = FinanceExpensesRouteImport.update({
  id: '/finance/expenses',
  path: '/finance/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/admin/teachers',
  path: '/admin/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStockRoute = AdminStockRouteImport.update({
  id: '/admin/stock',
  path: '/admin/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarksRoute = AdminMarksRouteImport.update({
  id: '/admin/marks',
  path: '/admin/marks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/admin/library',
  path: '/admin/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHrRoute = AdminHrRouteImport.update({
  id: '/admin/hr',
  path: '/admin/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/admin/finance',
  path: '/admin/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommunicationRoute = AdminCommunicationRouteImport.update({
  id: '/admin/communication',
  path: '/admin/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/admin/calendar',
  path: '/admin/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAcademicsRoute = AdminAcademicsRouteImport.update({
  id: '/admin/academics',
  path: '/admin/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsitePortalParentRoute = WebsitePortalParentRouteImport.update({
  id: '/website/portal/parent',
  path: '/website/portal/parent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/academics': typeof AdminAcademicsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/marks': typeof AdminMarksRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/fees': typeof FinanceFeesRoute
  '/finance/income': typeof FinanceIncomeRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/finance/structure': typeof FinanceStructureRoute
  '/library/books': typeof LibraryBooksRoute
  '/library/borrow': typeof LibraryBorrowRoute
  '/library/reports': typeof LibraryReportsRoute
  '/library/return': typeof LibraryReturnRoute
  '/stock/in': typeof StockInRoute
  '/stock/notifications': typeof StockNotificationsRoute
  '/stock/out': typeof StockOutRoute
  '/stock/products': typeof StockProductsRoute
  '/stock/reports': typeof StockReportsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/marks': typeof TeacherMarksRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
  '/website/about': typeof WebsiteAboutRoute
  '/website/admissions': typeof WebsiteAdmissionsRoute
  '/website/contact': typeof WebsiteContactRoute
  '/website/faq': typeof WebsiteFaqRoute
  '/website/gallery': typeof WebsiteGalleryRoute
  '/website/news': typeof WebsiteNewsRoute
  '/website/programs': typeof WebsiteProgramsRoute
  '/admin/': typeof AdminIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/stock/': typeof StockIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/website/': typeof WebsiteIndexRoute
  '/website/portal/parent': typeof WebsitePortalParentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/academics': typeof AdminAcademicsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/marks': typeof AdminMarksRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/fees': typeof FinanceFeesRoute
  '/finance/income': typeof FinanceIncomeRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/finance/structure': typeof FinanceStructureRoute
  '/library/books': typeof LibraryBooksRoute
  '/library/borrow': typeof LibraryBorrowRoute
  '/library/reports': typeof LibraryReportsRoute
  '/library/return': typeof LibraryReturnRoute
  '/stock/in': typeof StockInRoute
  '/stock/notifications': typeof StockNotificationsRoute
  '/stock/out': typeof StockOutRoute
  '/stock/products': typeof StockProductsRoute
  '/stock/reports': typeof StockReportsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/marks': typeof TeacherMarksRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
  '/website/about': typeof WebsiteAboutRoute
  '/website/admissions': typeof WebsiteAdmissionsRoute
  '/website/contact': typeof WebsiteContactRoute
  '/website/faq': typeof WebsiteFaqRoute
  '/website/gallery': typeof WebsiteGalleryRoute
  '/website/news': typeof WebsiteNewsRoute
  '/website/programs': typeof WebsiteProgramsRoute
  '/admin': typeof AdminIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/library': typeof LibraryIndexRoute
  '/stock': typeof StockIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/website': typeof WebsiteIndexRoute
  '/website/portal/parent': typeof WebsitePortalParentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/academics': typeof AdminAcademicsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/marks': typeof AdminMarksRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/fees': typeof FinanceFeesRoute
  '/finance/income': typeof FinanceIncomeRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/finance/structure': typeof FinanceStructureRoute
  '/library/books': typeof LibraryBooksRoute
  '/library/borrow': typeof LibraryBorrowRoute
  '/library/reports': typeof LibraryReportsRoute
  '/library/return': typeof LibraryReturnRoute
  '/stock/in': typeof StockInRoute
  '/stock/notifications': typeof StockNotificationsRoute
  '/stock/out': typeof StockOutRoute
  '/stock/products': typeof StockProductsRoute
  '/stock/reports': typeof StockReportsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/marks': typeof TeacherMarksRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
  '/website/about': typeof WebsiteAboutRoute
  '/website/admissions': typeof WebsiteAdmissionsRoute
  '/website/contact': typeof WebsiteContactRoute
  '/website/faq': typeof WebsiteFaqRoute
  '/website/gallery': typeof WebsiteGalleryRoute
  '/website/news': typeof WebsiteNewsRoute
  '/website/programs': typeof WebsiteProgramsRoute
  '/admin/': typeof AdminIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/stock/': typeof StockIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/website/': typeof WebsiteIndexRoute
  '/website/portal/parent': typeof WebsitePortalParentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/academics'
    | '/admin/attendance'
    | '/admin/calendar'
    | '/admin/communication'
    | '/admin/finance'
    | '/admin/hr'
    | '/admin/library'
    | '/admin/marks'
    | '/admin/settings'
    | '/admin/stock'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/auth/login'
    | '/finance/expenses'
    | '/finance/fees'
    | '/finance/income'
    | '/finance/reports'
    | '/finance/structure'
    | '/library/books'
    | '/library/borrow'
    | '/library/reports'
    | '/library/return'
    | '/stock/in'
    | '/stock/notifications'
    | '/stock/out'
    | '/stock/products'
    | '/stock/reports'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/courses'
    | '/teacher/marks'
    | '/teacher/reports'
    | '/teacher/timetable'
    | '/website/about'
    | '/website/admissions'
    | '/website/contact'
    | '/website/faq'
    | '/website/gallery'
    | '/website/news'
    | '/website/programs'
    | '/admin/'
    | '/finance/'
    | '/library/'
    | '/stock/'
    | '/teacher/'
    | '/website/'
    | '/website/portal/parent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/academics'
    | '/admin/attendance'
    | '/admin/calendar'
    | '/admin/communication'
    | '/admin/finance'
    | '/admin/hr'
    | '/admin/library'
    | '/admin/marks'
    | '/admin/settings'
    | '/admin/stock'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/auth/login'
    | '/finance/expenses'
    | '/finance/fees'
    | '/finance/income'
    | '/finance/reports'
    | '/finance/structure'
    | '/library/books'
    | '/library/borrow'
    | '/library/reports'
    | '/library/return'
    | '/stock/in'
    | '/stock/notifications'
    | '/stock/out'
    | '/stock/products'
    | '/stock/reports'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/courses'
    | '/teacher/marks'
    | '/teacher/reports'
    | '/teacher/timetable'
    | '/website/about'
    | '/website/admissions'
    | '/website/contact'
    | '/website/faq'
    | '/website/gallery'
    | '/website/news'
    | '/website/programs'
    | '/admin'
    | '/finance'
    | '/library'
    | '/stock'
    | '/teacher'
    | '/website'
    | '/website/portal/parent'
  id:
    | '__root__'
    | '/'
    | '/admin/academics'
    | '/admin/attendance'
    | '/admin/calendar'
    | '/admin/communication'
    | '/admin/finance'
    | '/admin/hr'
    | '/admin/library'
    | '/admin/marks'
    | '/admin/settings'
    | '/admin/stock'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/auth/login'
    | '/finance/expenses'
    | '/finance/fees'
    | '/finance/income'
    | '/finance/reports'
    | '/finance/structure'
    | '/library/books'
    | '/library/borrow'
    | '/library/reports'
    | '/library/return'
    | '/stock/in'
    | '/stock/notifications'
    | '/stock/out'
    | '/stock/products'
    | '/stock/reports'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/courses'
    | '/teacher/marks'
    | '/teacher/reports'
    | '/teacher/timetable'
    | '/website/about'
    | '/website/admissions'
    | '/website/contact'
    | '/website/faq'
    | '/website/gallery'
    | '/website/news'
    | '/website/programs'
    | '/admin/'
    | '/finance/'
    | '/library/'
    | '/stock/'
    | '/teacher/'
    | '/website/'
    | '/website/portal/parent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAcademicsRoute: typeof AdminAcademicsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCommunicationRoute: typeof AdminCommunicationRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminHrRoute: typeof AdminHrRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminMarksRoute: typeof AdminMarksRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStockRoute: typeof AdminStockRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AuthLoginRoute: typeof AuthLoginRoute
  FinanceExpensesRoute: typeof FinanceExpensesRoute
  FinanceFeesRoute: typeof FinanceFeesRoute
  FinanceIncomeRoute: typeof FinanceIncomeRoute
  FinanceReportsRoute: typeof FinanceReportsRoute
  FinanceStructureRoute: typeof FinanceStructureRoute
  LibraryBooksRoute: typeof LibraryBooksRoute
  LibraryBorrowRoute: typeof LibraryBorrowRoute
  LibraryReportsRoute: typeof LibraryReportsRoute
  LibraryReturnRoute: typeof LibraryReturnRoute
  StockInRoute: typeof StockInRoute
  StockNotificationsRoute: typeof StockNotificationsRoute
  StockOutRoute: typeof StockOutRoute
  StockProductsRoute: typeof StockProductsRoute
  StockReportsRoute: typeof StockReportsRoute
  TeacherAssignmentsRoute: typeof TeacherAssignmentsRoute
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherCoursesRoute: typeof TeacherCoursesRoute
  TeacherMarksRoute: typeof TeacherMarksRoute
  TeacherReportsRoute: typeof TeacherReportsRoute
  TeacherTimetableRoute: typeof TeacherTimetableRoute
  WebsiteAboutRoute: typeof WebsiteAboutRoute
  WebsiteAdmissionsRoute: typeof WebsiteAdmissionsRoute
  WebsiteContactRoute: typeof WebsiteContactRoute
  WebsiteFaqRoute: typeof WebsiteFaqRoute
  WebsiteGalleryRoute: typeof WebsiteGalleryRoute
  WebsiteNewsRoute: typeof WebsiteNewsRoute
  WebsiteProgramsRoute: typeof WebsiteProgramsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  StockIndexRoute: typeof StockIndexRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  WebsiteIndexRoute: typeof WebsiteIndexRoute
  WebsitePortalParentRoute: typeof WebsitePortalParentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/': {
      id: '/website/'
      path: '/website'
      fullPath: '/website/'
      preLoaderRoute: typeof WebsiteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/': {
      id: '/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof StockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/programs': {
      id: '/website/programs'
      path: '/website/programs'
      fullPath: '/website/programs'
      preLoaderRoute: typeof WebsiteProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/news': {
      id: '/website/news'
      path: '/website/news'
      fullPath: '/website/news'
      preLoaderRoute: typeof WebsiteNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/gallery': {
      id: '/website/gallery'
      path: '/website/gallery'
      fullPath: '/website/gallery'
      preLoaderRoute: typeof WebsiteGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/faq': {
      id: '/website/faq'
      path: '/website/faq'
      fullPath: '/website/faq'
      preLoaderRoute: typeof WebsiteFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/contact': {
      id: '/website/contact'
      path: '/website/contact'
      fullPath: '/website/contact'
      preLoaderRoute: typeof WebsiteContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/admissions': {
      id: '/website/admissions'
      path: '/website/admissions'
      fullPath: '/website/admissions'
      preLoaderRoute: typeof WebsiteAdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/about': {
      id: '/website/about'
      path: '/website/about'
      fullPath: '/website/about'
      preLoaderRoute: typeof WebsiteAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/timetable': {
      id: '/teacher/timetable'
      path: '/teacher/timetable'
      fullPath: '/teacher/timetable'
      preLoaderRoute: typeof TeacherTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/reports': {
      id: '/teacher/reports'
      path: '/teacher/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof TeacherReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/marks': {
      id: '/teacher/marks'
      path: '/teacher/marks'
      fullPath: '/teacher/marks'
      preLoaderRoute: typeof TeacherMarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/courses': {
      id: '/teacher/courses'
      path: '/teacher/courses'
      fullPath: '/teacher/courses'
      preLoaderRoute: typeof TeacherCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/teacher/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/assignments': {
      id: '/teacher/assignments'
      path: '/teacher/assignments'
      fullPath: '/teacher/assignments'
      preLoaderRoute: typeof TeacherAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/reports': {
      id: '/stock/reports'
      path: '/stock/reports'
      fullPath: '/stock/reports'
      preLoaderRoute: typeof StockReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/products': {
      id: '/stock/products'
      path: '/stock/products'
      fullPath: '/stock/products'
      preLoaderRoute: typeof StockProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/out': {
      id: '/stock/out'
      path: '/stock/out'
      fullPath: '/stock/out'
      preLoaderRoute: typeof StockOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/notifications': {
      id: '/stock/notifications'
      path: '/stock/notifications'
      fullPath: '/stock/notifications'
      preLoaderRoute: typeof StockNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/in': {
      id: '/stock/in'
      path: '/stock/in'
      fullPath: '/stock/in'
      preLoaderRoute: typeof StockInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/return': {
      id: '/library/return'
      path: '/library/return'
      fullPath: '/library/return'
      preLoaderRoute: typeof LibraryReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/reports': {
      id: '/library/reports'
      path: '/library/reports'
      fullPath: '/library/reports'
      preLoaderRoute: typeof LibraryReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/borrow': {
      id: '/library/borrow'
      path: '/library/borrow'
      fullPath: '/library/borrow'
      preLoaderRoute: typeof LibraryBorrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/books': {
      id: '/library/books'
      path: '/library/books'
      fullPath: '/library/books'
      preLoaderRoute: typeof LibraryBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/structure': {
      id: '/finance/structure'
      path: '/finance/structure'
      fullPath: '/finance/structure'
      preLoaderRoute: typeof FinanceStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/reports': {
      id: '/finance/reports'
      path: '/finance/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof FinanceReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/income': {
      id: '/finance/income'
      path: '/finance/income'
      fullPath: '/finance/income'
      preLoaderRoute: typeof FinanceIncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/fees': {
      id: '/finance/fees'
      path: '/finance/fees'
      fullPath: '/finance/fees'
      preLoaderRoute: typeof FinanceFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/expenses': {
      id: '/finance/expenses'
      path: '/finance/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof FinanceExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/admin/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stock': {
      id: '/admin/stock'
      path: '/admin/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AdminStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/marks': {
      id: '/admin/marks'
      path: '/admin/marks'
      fullPath: '/admin/marks'
      preLoaderRoute: typeof AdminMarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/library': {
      id: '/admin/library'
      path: '/admin/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hr': {
      id: '/admin/hr'
      path: '/admin/hr'
      fullPath: '/admin/hr'
      preLoaderRoute: typeof AdminHrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/admin/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/communication': {
      id: '/admin/communication'
      path: '/admin/communication'
      fullPath: '/admin/communication'
      preLoaderRoute: typeof AdminCommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/admin/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/academics': {
      id: '/admin/academics'
      path: '/admin/academics'
      fullPath: '/admin/academics'
      preLoaderRoute: typeof AdminAcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/portal/parent': {
      id: '/website/portal/parent'
      path: '/website/portal/parent'
      fullPath: '/website/portal/parent'
      preLoaderRoute: typeof WebsitePortalParentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAcademicsRoute: AdminAcademicsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCommunicationRoute: AdminCommunicationRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminHrRoute: AdminHrRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminMarksRoute: AdminMarksRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStockRoute: AdminStockRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AuthLoginRoute: AuthLoginRoute,
  FinanceExpensesRoute: FinanceExpensesRoute,
  FinanceFeesRoute: FinanceFeesRoute,
  FinanceIncomeRoute: FinanceIncomeRoute,
  FinanceReportsRoute: FinanceReportsRoute,
  FinanceStructureRoute: FinanceStructureRoute,
  LibraryBooksRoute: LibraryBooksRoute,
  LibraryBorrowRoute: LibraryBorrowRoute,
  LibraryReportsRoute: LibraryReportsRoute,
  LibraryReturnRoute: LibraryReturnRoute,
  StockInRoute: StockInRoute,
  StockNotificationsRoute: StockNotificationsRoute,
  StockOutRoute: StockOutRoute,
  StockProductsRoute: StockProductsRoute,
  StockReportsRoute: StockReportsRoute,
  TeacherAssignmentsRoute: TeacherAssignmentsRoute,
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherCoursesRoute: TeacherCoursesRoute,
  TeacherMarksRoute: TeacherMarksRoute,
  TeacherReportsRoute: TeacherReportsRoute,
  TeacherTimetableRoute: TeacherTimetableRoute,
  WebsiteAboutRoute: WebsiteAboutRoute,
  WebsiteAdmissionsRoute: WebsiteAdmissionsRoute,
  WebsiteContactRoute: WebsiteContactRoute,
  WebsiteFaqRoute: WebsiteFaqRoute,
  WebsiteGalleryRoute: WebsiteGalleryRoute,
  WebsiteNewsRoute: WebsiteNewsRoute,
  WebsiteProgramsRoute: WebsiteProgramsRoute,
  AdminIndexRoute: AdminIndexRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  StockIndexRoute: StockIndexRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  WebsiteIndexRoute: WebsiteIndexRoute,
  WebsitePortalParentRoute: WebsitePortalParentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
