/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as NewsRouteImport } from './routes/news'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PortalParentRouteImport } from './routes/portal.parent'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminStockRouteImport } from './routes/admin.stock'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminMarksRouteImport } from './routes/admin.marks'
import { Route as AdminLibraryRouteImport } from './routes/admin.library'
import { Route as AdminHrRouteImport } from './routes/admin.hr'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminCommunicationRouteImport } from './routes/admin.communication'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminAcademicsRouteImport } from './routes/admin.academics'

const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalParentRoute = PortalParentRouteImport.update({
  id: '/portal/parent',
  path: '/portal/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/admin/teachers',
  path: '/admin/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStockRoute = AdminStockRouteImport.update({
  id: '/admin/stock',
  path: '/admin/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarksRoute = AdminMarksRouteImport.update({
  id: '/admin/marks',
  path: '/admin/marks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/admin/library',
  path: '/admin/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHrRoute = AdminHrRouteImport.update({
  id: '/admin/hr',
  path: '/admin/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/admin/finance',
  path: '/admin/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommunicationRoute = AdminCommunicationRouteImport.update({
  id: '/admin/communication',
  path: '/admin/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/admin/calendar',
  path: '/admin/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAcademicsRoute = AdminAcademicsRouteImport.update({
  id: '/admin/academics',
  path: '/admin/academics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/programs': typeof ProgramsRoute
  '/admin/academics': typeof AdminAcademicsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/marks': typeof AdminMarksRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/portal/parent': typeof PortalParentRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/programs': typeof ProgramsRoute
  '/admin/academics': typeof AdminAcademicsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/marks': typeof AdminMarksRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/portal/parent': typeof PortalParentRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/programs': typeof ProgramsRoute
  '/admin/academics': typeof AdminAcademicsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/marks': typeof AdminMarksRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/portal/parent': typeof PortalParentRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/news'
    | '/programs'
    | '/admin/academics'
    | '/admin/attendance'
    | '/admin/calendar'
    | '/admin/communication'
    | '/admin/finance'
    | '/admin/hr'
    | '/admin/library'
    | '/admin/marks'
    | '/admin/settings'
    | '/admin/stock'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/auth/login'
    | '/portal/parent'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/news'
    | '/programs'
    | '/admin/academics'
    | '/admin/attendance'
    | '/admin/calendar'
    | '/admin/communication'
    | '/admin/finance'
    | '/admin/hr'
    | '/admin/library'
    | '/admin/marks'
    | '/admin/settings'
    | '/admin/stock'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/auth/login'
    | '/portal/parent'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/news'
    | '/programs'
    | '/admin/academics'
    | '/admin/attendance'
    | '/admin/calendar'
    | '/admin/communication'
    | '/admin/finance'
    | '/admin/hr'
    | '/admin/library'
    | '/admin/marks'
    | '/admin/settings'
    | '/admin/stock'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/auth/login'
    | '/portal/parent'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  NewsRoute: typeof NewsRoute
  ProgramsRoute: typeof ProgramsRoute
  AdminAcademicsRoute: typeof AdminAcademicsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCommunicationRoute: typeof AdminCommunicationRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminHrRoute: typeof AdminHrRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminMarksRoute: typeof AdminMarksRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStockRoute: typeof AdminStockRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AuthLoginRoute: typeof AuthLoginRoute
  PortalParentRoute: typeof PortalParentRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/parent': {
      id: '/portal/parent'
      path: '/portal/parent'
      fullPath: '/portal/parent'
      preLoaderRoute: typeof PortalParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/admin/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stock': {
      id: '/admin/stock'
      path: '/admin/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AdminStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/marks': {
      id: '/admin/marks'
      path: '/admin/marks'
      fullPath: '/admin/marks'
      preLoaderRoute: typeof AdminMarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/library': {
      id: '/admin/library'
      path: '/admin/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hr': {
      id: '/admin/hr'
      path: '/admin/hr'
      fullPath: '/admin/hr'
      preLoaderRoute: typeof AdminHrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/admin/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/communication': {
      id: '/admin/communication'
      path: '/admin/communication'
      fullPath: '/admin/communication'
      preLoaderRoute: typeof AdminCommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/admin/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/academics': {
      id: '/admin/academics'
      path: '/admin/academics'
      fullPath: '/admin/academics'
      preLoaderRoute: typeof AdminAcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  NewsRoute: NewsRoute,
  ProgramsRoute: ProgramsRoute,
  AdminAcademicsRoute: AdminAcademicsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCommunicationRoute: AdminCommunicationRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminHrRoute: AdminHrRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminMarksRoute: AdminMarksRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStockRoute: AdminStockRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AuthLoginRoute: AuthLoginRoute,
  PortalParentRoute: PortalParentRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
